/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lv.rigacoding.blackjack;

import data.*;
import graphic.*;// * ļauj importēt visas klases pakā

/**
 *
 * @author Ilzīte
 */
public class BlackJackForm extends javax.swing.JFrame {
Game game;
CardHolder dealerCards;
CardHolder playerCards;
    /**
     * Creates new form BlackJackForm
     */
    public BlackJackForm() {
        initComponents();
          
        game = new Game();
        dealerCards = new CardHolder();// klasē konstruktoram jābūt publiskam
        playerCards = new CardHolder();
       
        dealerPanel.add(dealerCards);
        playerPanel.add(playerCards);//pievieno kārtis panelim grafiskajā daļā
        
        
        startNewGame();
    }
    
    private void startNewGame(){
        this.dealCardButton.setVisible(true);
        this.dealerPointsLabel.setVisible(false);
        this.informationLabel.setVisible(false);
        this.playAgainButton.setVisible(false);
        this.stopButton.setVisible(true);
        
        game.startNewGameUI();
        refreshTable();
    }
    private void refreshTable(){
        this.dealerCards.Clear();
        this.playerCards.Clear();
        for (Card card : this.game.getDealerCards()){
            this.dealerCards.addCard(new CardImage(card));
        }
        
        for (Card card : this.game.getPlayerCards()){
            this.playerCards.addCard(new CardImage(card));
        }
        
        this.playerPointsLabel.setText("Punkti: " + this.game.getPlayerPoints());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dealerPanel = new javax.swing.JPanel();
        playerPanel = new javax.swing.JPanel();
        dealerPointsLabel = new javax.swing.JLabel();
        playerPointsLabel = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        dealCardButton = new javax.swing.JButton();
        informationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dealerPanel.setBackground(new java.awt.Color(150, 150, 150));

        playerPanel.setBackground(new java.awt.Color(150, 150, 150));

        dealerPointsLabel.setText("Dīlera punkti");

        playerPointsLabel.setText("Spēlētāja punkti");

        playAgainButton.setText("Spēlēt vēlreiz");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Pietiek");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        dealCardButton.setText("Vēl kārti");
        dealCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealCardButtonActionPerformed(evt);
            }
        });

        informationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        informationLabel.setText("paziņojums");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dealerPointsLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(playerPointsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(informationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playAgainButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addComponent(stopButton)
                .addGap(18, 18, 18)
                .addComponent(dealCardButton)
                .addGap(28, 28, 28))
            .addComponent(playerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dealerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dealerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPointsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(informationLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerPointsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stopButton)
                        .addComponent(dealCardButton)
                        .addComponent(playAgainButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        // TODO add your handling code here:
        startNewGame();
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
       
        game.dealerTurn();
        refreshTable();
        
        this.dealerPointsLabel.setVisible(true);
        this.dealerPointsLabel.setText("Punkti: " + game.getDealerPoints());
        this.informationLabel.setVisible(true);
        this.informationLabel.setText(game.getResult());
        
        this.dealCardButton.setVisible(false);
        this.stopButton.setVisible(false);
        this.playAgainButton.setVisible(true);
        
    }//GEN-LAST:event_stopButtonActionPerformed

    private void dealCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealCardButtonActionPerformed
        game.givePlayerCard();
        if(game.getPlayerPoints() < 21){
        
        refreshTable();}
        else{
            this.stopButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_dealCardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJackForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dealCardButton;
    private javax.swing.JPanel dealerPanel;
    private javax.swing.JLabel dealerPointsLabel;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JLabel playerPointsLabel;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
